### ISSUE TITLE
actionPrintText will append 'U@' at the beginning

### ISSUE THREAD

**Issue by c19354837** [star-micronics/StarXpand-SDK-Android#25] opened 2024-06-06 12:36 UTC
## Description
![image](https://github.com/star-micronics/StarXpand-SDK-Android/assets/8470613/6aab623b-bb20-40de-aa8c-21c4b15a2544)

## Your device where the bug occurs 
 - Device: 
    *Redmi K40*
 - OS:
    *Hyper OS 23.12.6 *
 - Browser: 
    */*
 - Version
    */*

## Your printer
- Model Names:
    *STP 7002️⃣*
- Firmware Version:
    *unkonw*
- Interface:
    *Ethernet*

## Your development environment
The result of executing the command `ver` on Windows, `sw_vers` on macOS, `uname –a` on Linux, or these equivalent commands.

## To Reproduce
1. run the demo
2. comment the logo print
3. click print

## Expected behavior
without 'U@'

**Comment by Tatsuki-Yamamoto2731** [comment] 2024-06-07 00:19
@c19354837 We have never evaluated our software on Xiaomi HyperOS, therefore, I think it is difficult for us to recreate the problem on our side. So, I would like to confirm more information about this issue.

My understanding:
On Xiaomi HyperOS, when a logo is added on the top of a receipt, there will be no problem.
However, when a logo is NOT added on the top of a receipt, 'U@' will be printed at the beginning, and "styleAlignment(Alignment.Center)" will not work.

My understanding is correct?

And regarding your photo, "without logo" receipt is created by removed (commented out) "actionPrintImage()" intentionally?

**Comment by c19354837** [comment] 2024-06-07 06:57
@Tatsuki-Yamamoto2731 Yes, the align is OK, just the 'U@' is wired. Remove [PrintingActivity.kt#L92](https://github.com/star-micronics/StarXpand-SDK-Android/blob/main/app/src/main/java/com/starmicronics/starxpandsdk/PrintingActivity.kt#L92) , 'U@' will come out.

I've tested in other devices, get same result:
![image](https://github.com/star-micronics/StarXpand-SDK-Android/assets/8470613/b19f0d2f-4ee5-4d22-9d25-4285a775e28d)

**Comment by Tatsuki-Yamamoto2731** [comment] 2024-06-07 07:36
@c19354837 Thank you for your answer.
It seems that the issue is caused on various Android-based OS. Maybe it is related to printer settings.
Then, could you please do self-printing and take the photo? From self-printing, you can see printer setting information.

How to do self-printing:
Turn the power ON, while holding down the switch, with the cover closed.

**Comment by Tatsuki-Yamamoto2731** [comment] 2024-09-30 09:02
Not updated for more than 3 months, therefore I closed this issue. If you still have the same issue, please reopen this issue.

**Closed by Tatsuki-Yamamoto2731** 2024-09-30 09:02 UTC
Labels: Status: question
